#name: Auto publish Github repository to cPanel
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy-production:
#    name: Deploy Project to PRODUCTION Server
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2.1.0
#        with:
#          fetch-depth: 2
#      - name: Setup Deployer to cPanel
#        uses: atymic/deployer-php-action@master
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          ssh-known-hosts: ${{ secrets.SSH_HOST }}
